name: Auto Release Action
on: 
  push: 
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

env:
  Version: Init
  Release: Init
  isPreRelease: true
  ChangeLog: Init
  CommitMessage: Init

jobs:
  AutoRelease: 
    name: Auto Release
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.6'

    - name: Python Pip Install
      uses: logikal-code/pip-install@v1.0.0

    - name: Get Version & Set GITHUB_ENV
      run: |
        $vc = "${{ github.event.head_commit.message }}" -split "  "
        echo "$vc"
        echo "Version=$($vc[0])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "CommitMessage=$($vc[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Release=$($vc[2])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        if ( $vc[2] -eq 'Release' ){
          echo 'isPreRelease=false' | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }

        echo (Get-Content ./changelog.txt)

    - name: Dist NoConsole ${{ env.Version }} Compress Version
      run: |
        pyinstaller --distpath ./NoCLI/ -D -i ./musync_data/Musync.ico ./MusyncSavDecodeGUI.py -w --clean
        Compress-Archive -LiteralPath ./NoCLI/MusyncSavDecodeGUI/ -DestinationPath ("./MusyncSavDecodeGUI_NoConsole_${{ env.Version }}.zip")
    - name: Dist NoConsole ${{ env.Version }} AllInOne Version
      run: |
        pyinstaller --distpath ./ -F -i ./musync_data/Musync.ico ./MusyncSavDecodeGUI.py -w
        Rename-Item -Path ./MusyncSavDecodeGUI.exe -NewName ("MusyncSavDecodeGUI_NoConsole_${{ env.Version }}_AllInOne.exe")
    - name: Dist WithConsole ${{ env.Version }} Compress Version
      run: |
        pyinstaller --distpath ./WithCLI/ -D -i ./musync_data/Musync.ico ./MusyncSavDecodeGUI.py
        Compress-Archive -LiteralPath ./WithCLI/MusyncSavDecodeGUI/ -DestinationPath ("./MusyncSavDecodeGUI_WithConsole_${{ env.Version }}.zip")
    - name: Dist WithConsole ${{ env.Version }} AllInOne Version
      run: |
        pyinstaller --distpath ./ -F -i ./musync_data/Musync.ico ./MusyncSavDecodeGUI.py
        Rename-Item -Path ./MusyncSavDecodeGUI.exe -NewName ("MusyncSavDecodeGUI_WithConsole_${{ env.Version }}_AllInOne.exe")

    - name: Commit Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: ${{ env.Release }}  ${{ env.CommitMessage }}  < Auto Release >
        tag_name: ${{ env.Version }}
        draft: false
        body_path: ${{ github.workspace }}/changelog.txt
        prerelease: ${{ env.isPreRelease }}
        files: |
          ./MusyncSavDecodeGUI_NoConsole_${{ env.Version }}.zip
          ./MusyncSavDecodeGUI_NoConsole_${{ env.Version }}_AllInOne.exe
          ./MusyncSavDecodeGUI_WithConsole_${{ env.Version }}.zip
          ./MusyncSavDecodeGUI_WithConsole_${{ env.Version }}_AllInOne.exe
